In [1]:
import numpy as np

In [7]:
#1運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#是
array1 = np.array([[10, 8], [3, 5]])
array2=np.linalg.inv(array1)
Ma1a2=array1 @ array2
array1,array2,Ma1a2

(array([[10,  8],
        [ 3,  5]]),
 array([[ 0.19230769, -0.30769231],
        [-0.11538462,  0.38461538]]),
 array([[1., 0.],
        [0., 1.]]))

In [15]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(Ma1a2)
print ('特徵值w',w)
print ('特徵向量v',v) 

特徵值w [1. 1.]
特徵向量v [[1. 0.]
 [0. 1.]]


In [16]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(Ma1a2)
u

array([[0., 1.],
       [1., 0.]])

In [17]:
s

array([1., 1.])

In [18]:
vh

array([[0., 1.],
       [1., 0.]])